ldap:
    adminAccount: Administrator@touch.cn
    base: OU=广州**电子科技有限公司,DC=touch,DC=cn
    domainName: '@touch.cn'
    referral: follow
    url: ldap://172.209.60.5:389
    userDn: cn=Administrator,cn=Users,dc=touch,dc=cn
    userPwd: 00**

        
spring:
    main:
      allow-bean-definition-overriding: true
    jackson: 
      time-zone: GMT+8
      date-format:  yyyy-MM-dd HH:mm:ss
    freemarker:
        allow-request-override: false
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        request-context-attribute: request
        suffix: .html
        template-loader-path: classpath:/templates/,classpath:/templates/ftl/
    servlet:
        multipart:
            maxFileSize: 1000MB
            maxRequestSize: 1000MB


